version: '3.4'

networks:
  backend:

services:
  catalogdb:
    container_name: catalogdb
    restart: always
    ports:
      - "27020:27020"
    volumes:
      - mongo_data:/data/db
    command: ["mongod", "--port", "27020"]

  basketdb:
    container_name: basketdb
    restart: always
    ports:
      - "6379:6379"

  discountdb:
    container_name: discountdb
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin1234
      - POSTGRES_DB=DiscountDb 
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  pgadmin:
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=rico3d@live.com
      - PGADMIN_DEFAULT_PASSWORD=admin1234
    restart: always
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/root/.pgadmin

  catalogo.api:
    container_name: catalogo-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=mongodb://catalogdb:27020"
    depends_on:
      - catalogdb
    ports:
      - "8000:80"

  basket.api:
    container_name: basket-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "CacheSettings:ConnectionString=basketdb:6379"
      - "GrpcSettings:DiscountUrl=discount.grpc"
    depends_on:
      - basketdb 
    ports:
      - "8001:80"


  discount.api:
    container_name: discount-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=Server=discountdb;Port=5432;Database=DiscountDb;User Id=admin;Password=admin1234" 
    depends_on:
      - discountdb
    ports:
      - "8002:80"


  discount.grpc:
    container_name: discount-grpc
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=Server=discountdb;Port=5432;Database=DiscountDb;User Id=admin;Password=admin1234" 
    depends_on:
      - discountdb
    ports:
      - "8003:80"


  apigateway:
    container_name: api-gateway
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8004:80"


